services:
  trujotech-site:
    build:
      context: ../web/trujotech-site
    container_name: trujotech-site
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
    ports:
      - "3010:3000"
    networks:
      - trujonet

networks:
  trujonet:
    external: true
